### PR TITLE
Hierarchical Radiosity

### PR DESCRIPTION
**Pull request by jeschkies**
Hierarchical radiosity implementation after Hanrahan et al.
"A rapid hierarchical radiosity algorithm".

* Refine triangles with solid angle form factor estimate.
* Solve radiosity by push-pull.
* Refine links after push-pull.

 TODO:
* [x] Would be nice to split the huge radiosity.cpp, e.g. extract Hierarchical into a file.
* [ ] generic dfs everywhere.
* [x] Replace all recursions by stacks.
* [ ] Add statistics output.
* [x] More argument for radiosity to adjust, F_eps, A_eps, etc...
* [x] (Gouraud shading)
* [ ] Radiosity pictures and readme update
* [ ] Liturature references in readme and code
* [x] Merge Radiosity tests
* [x] Switch to form factor estimation from Cohen-Wallace

### CODE REVIEW

**Comment by jeschkies** [comment]
We probably do not want to replace the old implementation but have a second.

**Comment by boxdot** [comment]
Still TODO:
* Would be nice to split the huge radiosity.cpp, e.g. extract Hierarchical into a file.
* Use generic dfs everywhere.
* Replace all recursions by stacks.
* Add statistics output.
* More argument for radiosity to adjust, F_eps, A_eps, etc...

**Comment by jeschkies** [comment]
We should test `lib/types.h` and `lib/triangle.h` to up code coverage before merging.

**Comment by jeschkies** [comment]
Also, `HierarchicalRadiosity` should move to `lib/hierarchical_radiosity.cpp` before the merge.

**Comment by boxdot** [comment]
Let's slight less verbose and move it to `lib/hierarchical.cpp`

**Comment by jeschkies** [comment]
Blocked by https://github.com/jeschkies/renderer/pull/71

**Comment by jeschkies** [comment]
PR #73  should replace recursion.

**Comment by jeschkies** [comment]
Blocked by
* PR https://github.com/jeschkies/renderer/pull/75
* PR https://github.com/jeschkies/renderer/pull/74

**Comment by boxdot** [comment]
Closes #64

**Comment by boxdot** [comment]
Blocked by
* PR: #77

**Pull request merged**
